/*
 * VIDEO_PIXEL.C
 *
 * Created by: Skylar Gilfeather, Asli Kocak
 * On: March 2, 2022
 * 
 * 
 */

#include <stdlib.h>
#include <math.h>
#include "video_pixel.h"
#include "pnm.h"

/* convert_rgb_to_video()
 * 
 * Converts floats red, green and blue to video values.
 *
 * @param	float r			Float red value for given pixel
 * @param	float g			Float green value for given pixel
 * @param	float b			Float blue value for given pixel
 *
 * @returns  				a Video_pixel struct 
 * 
 * @expects		r, g, and b are floats generated by the  
 * 				original image denominator.
.*/
Video_pixel convert_rgb_to_video(struct Pnm_rgb pixel, unsigned denom)
{
    float r = (float)pixel.red; // / (float) denom;
    float g = (float)pixel.green; // / (float) denom;
    float b = (float)pixel.blue; // / (float) denom;

    Video_pixel v_pixel;
    v_pixel.y  =  0.299    * r + 0.587    * g + 0.114    * b;
    v_pixel.pb = -0.168736 * r - 0.331264 * g + 0.5      * b;
    v_pixel.pr =  0.5      * r - 0.418688 * g - 0.081312 * b;
    
    (void) denom;
    return v_pixel;
}

/* convert_video_to_rgb()
 *
 * Given a Video_pixel struct, creates and returns an 
 * appropriately formatted Pnm_rgb instance for 1 pixel
 *
 * @param Video_pixel		Contains values of 1 pixel
 *
 * @returns	Pnm_rgb of 1 pixel	
 * 
 * @expects	The Video_pixel block is non-null
 *
 */
struct Pnm_rgb convert_video_to_rgb(Video_pixel pixel, unsigned denom)
{
    float red, green, blue;
    unsigned r, g, b;

    red = 1.0 * pixel.y + 0.0 * pixel.pb + 1.402 * pixel.pr;
    green = 1.0 * pixel.y - 0.344136 * pixel.pb - 0.714136 * pixel.pr;
    blue = 1.0 * pixel.y + 1.772 * pixel.pb + 0.0 * pixel.pr;

   // fprintf(stderr, "red? %f\n", round(red)); // * denom);

    r = (unsigned) roundf(red); //* denom);
    g = (unsigned) roundf(green); // * denom);
    b = (unsigned) roundf(blue); // * denom); 
 
    (void)denom;
    
    struct Pnm_rgb new_pix;
    new_pix.red = r;
    new_pix.green = g;
    new_pix.blue = b;

    return new_pix;
}